module.exports = {
    email: `doItArtist${Date.now()}@auto.test`,
    password: 'JustDoIt1000',
    firstName: 'Max',
    lastName: 'Random',
    birthDay: 6,
    birthMonth: 4,
    birthYear: 40,
    location: 'Broadway',
    buildingNum: 63,
    zipCode: 65069,
    phoneNum: 380631555555,
    cvPath: './resources/cv-example.pdf',
    talent: 'Singer',
    style: 'Deep House',
    artisticName: 'Pearl',
    briefIntroduction: 'Very good singer',
    aboutSection: 'Singer from Ukraine',
    inBusiness: 1, // 1: 0-6 months; 2: 7-12 months; 3: 1-2 years;
    primaryFee: 100,
    primaryFeePricePeriod: 1, // 1 - 10 values
    secondaryFee: 200,
    secondaryFeePricePeriod: 2, // 1 - 10 values
    abilityToTravel: 'Europe',
    serviceOption: 'Random',
    serviceFee: 300,
    serviceFeePricePeriod: 3, // 1 - 10 values
    tag: 'MyTag',
    avatarPicture: './resources/avatarpicture.jpg',
    coverPhoto: './resources/coverpicture.jpg',
    cardPhoto: './resources/cardpicture.jpg',
    mainVideoLocation: 'New York',
    mainVideoHashtag: 'Good',
    mainVideoUrl: 'https://youtu.be/4se8fLrC3ds',
    firstAudioLocation: 'Odessa',
    firstAudioHashtag: 'Best',
    firstAudioUrl: 'https://soundcloud.com/migosatl/motor-sport',
    firstPictureLocation: 'Poland',
    firstPictureHashtag: 'Hello',
    firstPicturePath: './resources/picture_1.jpg',
};
